{{- if .Values.httpproxy.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "go-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-demo
  {{- with .Values.httpproxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: contour
  routes:
    - conditions:
        - prefix: {{ .Values.httpproxy.prefix }}
      pathRewritePolicy:
        replacePrefix:
          - replacement: {{ .Values.httpproxy.replacement }}
      services:
        - name: {{ include "go-demo.fullname" . }}
          port: {{ .Values.service.port }}
  virtualhost:
    fqdn:  {{ .Values.httpproxy.fqdn }}
{{- end }}
