replicaCount: 1

image:
  repository: ghcr.io/joostvdg
  pullPolicy: IfNotPresent
  tag: "0.2.0-9416b13"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

zipkin:
  host: localhost
  port: 9411

resources:
  limits:
    cpu: 250m
    memory: 64Mi
  requests:
    cpu: 250m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

httpproxy:
  enabled: false
  fqdn: chart-example.local
  prefix: /go-demo
  replacement: /